export const categorizedData = {
  frontend: [
    { img: "/skills/html5.svg", name: "HTML" },
    { img: "/skills/css3.svg", name: "CSS" },
    { img: "/skills/bootstrap.svg", name: "Bootstrap" },
    { img: "/skills/tailwind.svg", name: "Tailwind" },
    { img: "/skills/material-ui.svg", name: "Material UI" },
    { img: "/skills/javascript.svg", name: "Javascript" },
    { img: "/skills/typescript.svg", name: "Typescript" },
    { img: "/skills/react.svg", name: "React" },
    { img: "/skills/next.svg", name: "Next.js" },
    { img: "/skills/redux.svg", name: "Redux" },
    { img: "/skills/react-query.svg", name: "React Query" },
    { img: "/skills/formik.svg", name: "Formik" },
    { img: "/skills/shadcn.svg", name: "shadcn" },
  ],
  backend: [
    { img: "/skills/nodejs.svg", name: "Nodejs" },
    { img: "/skills/mongodb.svg", name: "Mongodb" },
    { img: "/skills/firebase.svg", name: "Firebase" },
    { img: "/skills/socket-io.svg", name: "Socket-io" },
    { img: "/skills/jwt.svg", name: "JWT" },
    { img: "/skills/json.svg", name: "DummyJSON" },
  ],
  tools: [
    { img: "/skills/git.svg", name: "Git" },
    { img: "/skills/github.svg", name: "Github" },
    { img: "/skills/npm.svg", name: "npm" },
    { img: "/skills/pnpm.svg", name: "pnpm" },
    { img: "/skills/yarn.svg", name: "yarn" },
    { img: "/skills/postman.svg", name: "Postman" },
    { img: "/skills/prettier.svg", name: "Prettier" },
    { img: "/skills/visual-studio-code.svg", name: "VS Code" },
    { img: "/skills/vercel.svg", name: "Vercel" },
    { img: "/skills/eslint.svg", name: "ESLint" },
    { img: "/skills/sourcegraph.svg", name: "Sourcegraph" },
    { img: "/skills/ubuntu.svg", name: "Ubuntu" },
    { img: "/skills/microsoft-windows.svg", name: "Windows" },
    { img: "/skills/linux-tux.svg", name: "Linux" },
  ],
};
