export const categorizedData = {
  frontend: [
    { img: "/skills/html5.svg", name: "HTML" },
    { img: "/skills/ejs.svg", name: "EJS" },
    { img: "/skills/css3.svg", name: "CSS" },
    { img: "/skills/bootstrap.svg", name: "Bootstrap" },
    { img: "/skills/tailwind.svg", name: "Tailwind" },
    { img: "/skills/material-ui.svg", name: "Material UI" },
    { img: "/skills/javascript.svg", name: "Javascript" },
    { img: "/skills/typescript.svg", name: "Typescript" },
    { img: "/skills/react.svg", name: "React" },
    { img: "/skills/next.svg", name: "Next.js" },
    { img: "/skills/vite.svg", name: "Vite.js" },
    { img: "/skills/astro.svg", name: "Astro" },
    { img: "/skills/react-router.svg", name: "React Router" },
    { img: "/skills/redux.svg", name: "Redux" },
    { img: "/skills/react-query.svg", name: "React Query" },
    { img: "/skills/formik.svg", name: "Formik" },
    { img: "/skills/shadcn.svg", name: "shadcn" },
    { img: "/skills/quill.svg", name: "Quill" },
    { img: "/skills/markdown.svg", name: "Markdown" },
  ],
  backend: [
    { img: "/skills/nodejs.svg", name: "Nodejs" },
    { img: "/skills/express.svg", name: "Express" },
    { img: "/skills/nest.svg", name: "Nest.js" },
    { img: "/skills/MySQL.svg", name: "MySQL" },
    { img: "/skills/mongodb.svg", name: "Mongodb" },
    { img: "/skills/dbeaver.svg", name: "DBeaver" },
    { img: "/skills/firebase.svg", name: "Firebase" },
    { img: "/skills/socket-io.svg", name: "Socket-io" },
    { img: "/skills/nodemailer.webp", name: "Nodemailer" },
    { img: "/skills/jwt.svg", name: "JWT" },
    { img: "/skills/json.svg", name: "JSON" },
    { img: "/skills/sheety.png", name: "Sheety" },
  ],
  tools: [
    { img: "/skills/powershell.svg", name: "Powershell" },
    { img: "/skills/git.svg", name: "Git" },
    { img: "/skills/github.svg", name: "Github" },
    { img: "/skills/npm.svg", name: "npm" },
    { img: "/skills/pnpm.svg", name: "pnpm" },
    { img: "/skills/yarn.svg", name: "yarn" },
    { img: "/skills/postman.svg", name: "Postman" },
    { img: "/skills/thunder-client.png", name: "Thunder Client" },
    { img: "/skills/prettier.svg", name: "Prettier" },
    { img: "/skills/visual-studio-code.svg", name: "VS Code" },
    { img: "/skills/vercel.svg", name: "Vercel" },
    { img: "/skills/railway.svg", name: "Railway" },
    { img: "/skills/eslint.svg", name: "ESLint" },
    { img: "/skills/sourcegraph.svg", name: "Sourcegraph" },
    { img: "/skills/ubuntu.svg", name: "Ubuntu" },
    { img: "/skills/microsoft-windows.svg", name: "Windows" },
    { img: "/skills/linux-tux.svg", name: "Linux" },
    { img: "/skills/wakatime.svg", name: "WakaTime" },
    { img: "/skills/trello.svg", name: "Trello" },
    { img: "/skills/swagger.svg", name: "Swagger" },
  ],
};
